name: Build and Deploy

on: [push]

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:prod

      - name: Upload build
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: www
          path: dist/sme-site #PATH OF BUILD WITH IS NAME IN PACKAGE.JSON

  run-deploy:
    runs-on: ubuntu-latest
    needs: run-build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: www
          path: dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          BRANCH: gh-pages
          FOLDER: dist
        env:
          EMAILAPIKEY: ${{ secrets.EMAILAPIKEY }}
